packages:
  - apps/*
  - packages/*

allowBuilds:
  "@swc/core": true
  canvas: true
  core-js: true
  omezarr-tilesource: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - omezarr-tilesource@0.7.0
