packages:
  - apps/*
  - packages/*

allowBuilds:
  "@swc/core": true
  canvas: true
  core-js: true
  omezarr-tilesource: true

minimumReleaseAgeExclude:
  - "@types/node@26.0.1"

onlyBuiltDependencies:
  - "@swc/core"
  - canvas
  - core-js
  - core-js-pure
  - esbuild
  - omezarr-tilesource
