import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore sidebar is autogenerated by typedoc and may not be available
import typedocSidebar from "./docs/api/typedoc-sidebar";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
  apiSidebar: [
    {
      type: "category",
      label: "API",
      link: {
        type: "doc",
        id: "api/index",
      },
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore sidebar is autogenerated by typedoc and may not be available
      items: (typedocSidebar as { items: unknown }).items,
    },
  ],
};

export default sidebars;
