name: ci
on:
  pull_request:
    branches:
      - main
      - development
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build packages
        run: pnpm run build:packages
  format:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Check formatting
        run: pnpm run fmt:check
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: pnpm run lint
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: pnpm run test
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          directory: coverage
          fail_ci_if_error: true
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
